# Generated by Django 5.2.1 on 2025-06-30 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(default='Local não definido', max_length=200)),
                ('numero_pessoas', models.IntegerField(default=0)),
                ('data_hora', models.DateTimeField()),
                ('duracao', models.CharField(default='1 hora', max_length=50)),
                ('tipo', models.CharField(default='Geral', max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos_imagens/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
