# Generated by Django 5.2.1 on 2025-07-01 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='eventos.evento')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='eventos.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'participante')},
            },
        ),
    ]
