# Generated by Django 5.2.1 on 2025-05-18 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='duracao',
            field=models.CharField(default='1 hora', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Local não definido', max_length=200),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_pessoas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='Geral', max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
    ]
